### ISSUE TITLE
level info tekens veranderen

### ISSUE THREAD

**Issue by DoveDoof** [DoveDoof/PiE_Serious_Maze#6]
Muur: 'x'
pad: 'o'

grotere en meer mazes.

**Comment by Mark-Boon** [comment]
muur x en pad o moet tegerlijkertijd met movement want daar stel ik nu in wat een muur is en wat niet (if ... ==1) ...

**Comment by DoveDoof** [comment]
Er zijn twee variabelen, het complete level en wat de speler kan zien (los_grid oid), je checkt of de beweging valid is in de los_grid, niet in het level lijkt me omdat dit in dezelfde classe zit.
In het level moet de info dus komen zoals hierboven beschreven.
De los matrix kan een ander teken gebruiken als je dat handiger vind (-1 voor muur, 0 voor pad, getallen voor getallen)
Dit hoeft dus niet tegelijkertijd.

**Comment by DoveDoof** [comment]
888381 fixt dit.
